// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type EmptyData struct {
}

type GeneralRes struct {
	Base
	Data EmptyData `json:"data"`
}

type LeaderboardRes struct {
	Base
	Data []Score `json:"scores"`
}

type Score struct {
	Username string `json:"username"`
	Score    int    `json:"score"`
}

type ScoreReq struct {
	Username string `json:"username"`
	Score    int    `json:"score"`
}
