# EXAMPLE
Name: "fly-service"
Host: "0.0.0.0"
Port: 8080
  
MySQL:
  Name: "fly"         
  User: "root"                  
  Password: "xxx"
  Host: "localhost"             
  Port: 3306                    

